#!/usr/bin/env bash
#shellcheck shell=bash

# Depends on piaware

sleep 10

# Check to see if we've already updated the stats url
if [ -f "/.statsurlupdated" ]; then
    # do nothing, sleep forever
    sleep 3600

else
    # attempt to update the url

    # check to see if our site statistics url has made it to the log yet
    if ! grep "site statistics URL:" /var/log/piaware/current > /dev/null; then
        # site statistics url not yet found, exit and try again
        exit 0
    fi

    STATSURL=$(grep "site statistics URL:" /var/log/piaware/current | tail -1 | cut -d "]" -f 2 | tr -d " " | cut -d ":" -f 4-)

    echo "[statsurlupdater] Updating SkyAware link to: ${STATSURL}"

    OLDURL="http://flightaware.com/"

    sed -i 's,'"${OLDURL}"','"${STATSURL}"',' /usr/share/dump1090-fa/html/index.html

    # touch a state file so this script knows not to process again
    touch /.statsurlupdated
    
fi
