#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -eo pipefail

exec \
    /usr/sbin/lighttpd \
    -f /etc/lighttpd/skyaware.lighttpd.conf \
    -D \
    2>&1 | awk -W Interactive '{print "[skyaware] " $0}'
