#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Depends on dump1090

set -eo pipefail

# shellcheck disable=SC2016
/usr/sbin/lighttpd \
    -f /etc/lighttpd/skyaware.lighttpd.conf \
    -D \
    2>&1 | stdbuf -o0 awk '{print "[skyaware] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    