#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Build the dump1090 command line based on piaware options
if [ -z "${BEASTHOST}" ]; then
  sleep 3600
else
  exec \
    socat -d -d TCP-LISTEN:30005,fork TCP:"${BEASTHOST}:${BEASTPORT}" 2>&1 | awk '{print "[beastrelay] " $0}'
fi
