#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Build the dump1090 command line based on piaware options
if [ -z "${BEASTHOST}" ]; then
  sleep 3600
else
  exec \
    socat -d -d TCP:"${BEASTHOST}:${BEASTPORT}" TCP:localhost:30004 2>&1 | awk '{print "[beastproxy] " $0}'
fi
