#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# When running with an external beast provider, we push the beast traffic
# into the local dump1090 instance. This allows JSON data to be written, 
# and SkyAware to function normally.

set -x

SOCAT_BIN="$(which socat)"
SOCAT_CMD=(-ls)

if [ "$VERBOSE_LOGGING" = "true" ]; then
  SOCAT_CMD+="-d -d"
fi

SOCAT_CMD+=("TCP:${BEASTHOST}:${BEASTPORT}")
SOCAT_CMD+=("TCP:localhost:30004")

if [ -z "${BEASTHOST}" ]; then
  sleep 3600
else
  # shellcheck disable=SC2016
  "${SOCAT_BIN}" "${SOCAT_CMD[@]}" \ \
    2>&1 | stdbuf -o0 awk '{print "[beastrelay] " $0}'
fi
