#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Don't continue if UAT not used
if [[ -n "$UAT_RECEIVER_HOST" ]]; then
  RUN_SKYAWARE978="true"
fi

if [[ -n "$UAT_RECEIVER_TYPE" ]]; then
  if [[ "$UAT_RECEIVER_TYPE" != "none" ]]; then
    RUN_SKYAWARE978="true"
  fi
fi

if [[ -n "$RUN_SKYAWARE978" ]]; then
  sleep 86400
  exit 0
fi

set -eo pipefail

# shellcheck disable=SC2016
skyaware978 \
  --connect 127.0.0.1:30978 \
  --json-dir "/run/skyaware978" \
  --lat "$LAT" \
  --lon "$LONG" \
  2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[skyaware978] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
