#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Don't continue if UAT_RECEIVER_HOST is set
if [[ -n "$UAT_RECEIVER_HOST" ]]; then
  sleep 86400
  exit 0
fi

# Don't continue if UAT_RECEIVER_TYPE is none | relay
case "${UAT_RECEIVER_TYPE:-none}" in
  none | relay)
    sleep 86400
    exit 0
  ;;
esac

set -eo pipefail

# shellcheck disable=SC2016
skyaware978 \
  --connect 127.0.0.1:30978 \
  --json-dir "/run/skyaware978" \
  --lat "$LAT" \
  --lon "$LONG" \
  2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[dump978] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
