#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,2154

source /scripts/common

# Remove existing piaware config
rm /etc/piaware.conf > /dev/null 2>&1 || true
touch /etc/piaware.conf

# piaware-config is very slow, as we have full control over the config file, just use a function to directly write the config settings into the config file
function piaware-config() {
    echo "$1 \"$2\"" | tee -a /etc/piaware.conf
}

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [[ -n "${USERNAME}" ]]; then
  echo "WARNING: USERNAME environment variable is DEPRECATED and does nothing"
fi
if [[ -n "${PASSWORD}" ]]; then
  echo "WARNING: PASSWORD environment variable is DEPRECATED and does nothing"
fi
if [ -z "${FEEDER_ID}" ]; then
  echo "INFO: no specific FEEDER_ID set, falling back to dynamic generated (/var/cache/piaware)"
  unset FEEDER_ID
else
  piaware-config feeder-id "${FEEDER_ID}"
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# If BINGMAPSAPIKEY is set, modify dump1090's config.js to include it
if [ -n "${BINGMAPSAPIKEY}" ]; then
  echo "INFO: setting BINGMAPSAPIKEY in /usr/share/skyaware/html/config.js"

  sed \
    -i \
    "/^BingMapsAPIKey = /c\BingMapsAPIKey = "'"'"${BINGMAPSAPIKEY}"'"'";" \
    /usr/share/skyaware/html/config.js

fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" >/etc/timezone
fi

# Set up piaware
piaware-config allow-auto-updates no
piaware-config allow-manual-updates no
piaware-config allow-mlat "${ALLOW_MLAT:-yes}"
piaware-config mlat-results "${MLAT_RESULTS:-yes}"

# If a BEASTHOST is specified
if [[ -n "$BEASTHOST" ]]; then
  if chk_enabled "${PIAWARE_MINIMAL}"; then
    piaware-config receiver-type "other"
  else
    piaware-config receiver-type "relay"
  fi
  piaware-config receiver-host "$BEASTHOST"
  piaware-config receiver-port "${BEASTPORT:-30005}"

# Default - rtlsdr mode
else
  piaware-config receiver-type "rtlsdr"
fi

if [[ -n "$RADARCAPE_HOST" ]]; then
  piaware-config receiver-type "radarcape"
  piaware-config radarcape-host "$RADARCAPE_HOST"
fi

# If a UAT_RECEIVER_HOST is specified
if [[ -n "$UAT_RECEIVER_HOST" ]]; then
  piaware-config uat-receiver-type "other"
  piaware-config uat-receiver-host "$UAT_RECEIVER_HOST"
  piaware-config uat-receiver-port "${UAT_RECEIVER_PORT:-30978}"

elif [[ "$UAT_RECEIVER_TYPE" == "rtlsdr" ]]; then
  piaware-config uat-receiver-type "sdr"

fi

MLAT_RESULTS_STRING="beast,listen,30105 ext_basestation,listen,30106 "

if [[ -n "$BEASTHOST" ]] && chk_enabled "${PIAWARE_MINIMAL}"; then
    # make it obvious the map is not available when PIAWARE_MINIMAL is set
    sed -i -e "s#'/skyaware.*/'#''#g" -e "s/Go to.*SkyAware Map/Map disabled/g" /var/www/html/index.js
else
    MLAT_RESULTS_STRING+="beast,connect,localhost:30104 "
fi

# If MLAT_RESULTS_BEAST_CONNECT is specified
if [[ -n "$MLAT_RESULTS_BEASTHOST" ]]; then
    MLAT_RESULTS_STRING+="beast,connect,${MLAT_RESULTS_BEASTHOST}:${MLAT_RESULTS_BEASTPORT:-30104} "
fi
piaware-config mlat-results-format "${MLAT_RESULTS_STRING}"

# Create log dir for piaware
mkdir -p /var/log/piaware
chown nobody:nogroup /var/log/piaware
mkdir -p /run/dump1090-fa
