#!/command/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

source /scripts/common

# Don't continue if UAT_RECEIVER_HOST isn't set
if [[ -z "$UAT_RECEIVER_HOST" ]]; then
    stop_service
fi

# shellcheck disable=SC2016
socat -d -d TCP-LISTEN:30978,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30978}" \
 2>&1 | stdbuf -o0 sed '/^$/d' | stdbuf -o0 awk '{print "[978json-splitter] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
