#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,2154
set -eo pipefail

source /scripts/common

# DEPRECATED
# this should no longer be needed but keep it around just in case
stop_service

# Don't continue if UAT_RECEIVER_HOST isn't set
if [[ -z "$UAT_RECEIVER_HOST" ]]; then
    stop_service
fi

# shellcheck disable=SC2016
exec "${s6wrap[@]}" socat -d -d TCP-LISTEN:30978,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30978}"
