#!/command/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

source /scripts/common

# Don't continue if BEASTHOST isn't set
if [[ -z "$BEASTHOST" ]]; then
    stop_service
fi

# Prepare beast-splitter command line
BEASTSPLITTER_BIN="/usr/local/bin/beast-splitter"
BEASTSPLITTER_CMD=("--net" "$BEASTHOST:${BEASTPORT:-30005}")
BEASTSPLITTER_CMD+=("--connect" "127.0.0.1:30004")

# shellcheck disable=SC2016
exec "${s6wrap[@]}" "${BEASTSPLITTER_BIN}" "${BEASTSPLITTER_CMD[@]}"
