#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,2154

source /scripts/common

# Don't continue if UAT not used
if [[ -n "$UAT_RECEIVER_TYPE" ]]; then
  if [[ "$UAT_RECEIVER_TYPE" != "none" ]]; then
    if [[ "$UAT_RECEIVER_TYPE" != "relay" ]]; then
      RUN_DUMP978="true"
    fi
  fi
fi

if [[ -z "$RUN_DUMP978" ]]; then
    stop_service
fi



# Set readsb binary
DUMP978_BIN="/usr/local/bin/dump978-fa"

# Listen on 0.0.0.0:DUMP978_RAW_PORT for raw messages
DUMP978_CMD=("--raw-port" "0.0.0.0:30978")

# Listen on 0.0.0.0:DUMP978_JSON_PORT for json messages
DUMP978_CMD+=("--json-port" "0.0.0.0:30979")

DUMP978_CMD+=("--format" "CS8")

# Handle "--sdr"
if [[ "$UAT_RECEIVER_TYPE" == "rtlsdr" ]]; then
    if [[ -n "${DUMP978_DEVICE}" ]]; then
        DUMP978_CMD+=("--sdr" "driver=rtlsdr,serial=${DUMP978_DEVICE}")
    else
        DUMP978_CMD+=("--sdr" "driver=rtlsdr")
    fi
fi

# Handle "--sdr-auto-gain"
if [[ -n "$DUMP978_SDR_AGC" ]]; then
    DUMP978_CMD+=("--sdr-auto-gain")
fi

# Handle "--sdr-gain"
if [[ -n "$UAT_SDR_GAIN" ]]; then
    DUMP978_CMD+=("--sdr-gain" "$UAT_SDR_GAIN")
fi

# Handle "--sdr-ppm"
if [[ -n "$UAT_SDR_PPM" ]]; then
    DUMP978_CMD+=("--sdr-ppm" "$UAT_SDR_PPM")
fi

if [[ -n "$DUMP978_JSON_STDOUT" ]]; then
    DUMP978_CMD+=("--json-stdout")
fi

set -eo pipefail

# shellcheck disable=SC2016
exec "${s6wrap[@]}" "${DUMP978_BIN}" "${DUMP978_CMD[@]}"
