#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,2154
set -eo pipefail

source /scripts/common

# Don't continue if ADSB not used
if [[ -n "$BEASTHOST" ]]; then
  RUN_DUMP1090="true"
fi
if [[ -n "$DUMP1090_DEVICE" ]]; then
  RUN_DUMP1090="true"
fi
if [[ -n "$RECEIVER_TYPE" ]]; then
  RUN_DUMP1090="true"
fi
if [[ -z "$RUN_DUMP1090" ]]; then
    stop_service
fi
if chk_enabled "${PIAWARE_MINIMAL}"; then
    stop_service
fi

mkdir -p /run/dump1090-fa

DUMP1090_BIN="/usr/local/bin/dump1090"

# Global settings
DUMP1090_CMD=("--quiet")
DUMP1090_CMD+=("--net")
DUMP1090_CMD+=("--fix")
DUMP1090_CMD+=("--json-location-accuracy" "2")
DUMP1090_CMD+=("--write-json" "/run/dump1090-fa")
DUMP1090_CMD+=("--net-bind-address" "0.0.0.0")

# use location from /var/cache/piaware/location.env
source /var/cache/piaware/location.env &>/dev/null || true
if [[ -n "$PIAWARE_LAT" ]] && [[ -n "$PIAWARE_LON" ]]; then
    DUMP1090_CMD+=("--lat" "$PIAWARE_LAT")
    DUMP1090_CMD+=("--lon" "$PIAWARE_LON")
fi

# Handle "--modeac"
if [[ "$ALLOW_MODEAC" == "yes" ]]; then
        DUMP1090_CMD+=("--modeac")
fi

# If a BEASTHOST is specified
if [[ -n "$BEASTHOST" ]]; then
    DUMP1090_CMD+=("--net-only")

# Default - rtlsdr mode
else
    DUMP1090_CMD+=("--device-type" "rtlsdr")

    if [[ -n "$DUMP1090_DEVICE" ]]; then
        DUMP1090_CMD+=("--device" "$DUMP1090_DEVICE")
    fi

    if [[ -n "$RTLSDR_PPM" ]]; then
        DUMP1090_CMD+=("--ppm" "$RTLSDR_PPM")
    fi

    if [[ -n "$RTLSDR_GAIN" ]]; then
        DUMP1090_CMD+=("--gain" "$RTLSDR_GAIN")
    fi

    if [[ -n "$DUMP1090_ADAPTIVE_RANGE" ]]; then
        DUMP1090_CMD+=("--adaptive-range")
    fi

    if [[ -n "$DUMP1090_ADAPTIVE_RANGE_TARGET" ]]; then
        DUMP1090_CMD+=("--adaptive-range-target" "$DUMP1090_ADAPTIVE_RANGE_TARGET")
    fi

    if [[ -n "$DUMP1090_ADAPTIVE_BURST" ]]; then
        DUMP1090_CMD+=("--adaptive-burst")
    fi

    if [[ -n "$DUMP1090_ADAPTIVE_MIN_GAIN" ]]; then
        DUMP1090_CMD+=("--adaptive-min-gain" "$DUMP1090_ADAPTIVE_MIN_GAIN")
    fi

    if [[ -n "$DUMP1090_ADAPTIVE_MAX_GAIN" ]]; then
        DUMP1090_CMD+=("--adaptive-max-gain" "$DUMP1090_ADAPTIVE_MAX_GAIN")
    fi

    if [[ -n "$DUMP1090_ADAPTIVE_DUTY_CYCLE" ]]; then
        DUMP1090_CMD+=("--adaptive-duty-cycle" "$DUMP1090_ADAPTIVE_DUTY_CYCLE")
    fi
fi

# shellcheck disable=SC2016
# run dump1090
exec "${s6wrap[@]}" "${DUMP1090_BIN}" "${DUMP1090_CMD[@]}"
