#!/command/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Depends on beastproxy (only if an external beasthost is used) and dump1090

mkdir -p /run/piaware

PIAWARE_BIN="/usr/bin/piaware"
PIAWARE_CMD=(-plainlog)
PIAWARE_CMD+=(-statusfile /run/piaware/status.json)

if [ "$VERBOSE_LOGGING" = "true" ]; then
  PIAWARE_CMD+=(-debug)
fi

# shellcheck disable=SC2016
"${PIAWARE_BIN}" "${PIAWARE_CMD[@]}" \
  2>&1 | stdbuf -o0 sed '/^$/d' | stdbuf -o0 awk '{print "[piaware] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
