#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,2154
set -eo pipefail

source /scripts/common

# Depends on beastproxy (only if an external beasthost is used) and dump1090

mkdir -p /run/piaware

PIAWARE_BIN="/usr/bin/piaware"
PIAWARE_CMD=(-plainlog)
PIAWARE_CMD+=(-statusfile /run/piaware/status.json)

if [ "$VERBOSE_LOGGING" = "true" ]; then
  PIAWARE_CMD+=(-debug)
fi

# shellcheck disable=SC2016
exec "${s6wrap[@]}" "${PIAWARE_BIN}" "${PIAWARE_CMD[@]}" > >(tee -a /var/log/piaware/current)
