#!/command/with-contenv bash
# shellcheck shell=bash

# Depends on dump1090

set -eo pipefail

source /scripts/common

# shellcheck disable=SC2016
exec "${s6wrap[@]}" /usr/sbin/lighttpd \
    -f /etc/lighttpd/skyaware.lighttpd.conf \
    -D
