#!/command/with-contenv bash
# shellcheck shell=bash disable=SC1091,2154

source /scripts/common

# Don't continue if UAT not used
if [[ -n "$UAT_RECEIVER_HOST" ]]; then
  RUN_SKYAWARE978="true"
fi

if [[ -n "$UAT_RECEIVER_TYPE" ]]; then
  if [[ "$UAT_RECEIVER_TYPE" != "none" ]]; then
    RUN_SKYAWARE978="true"
  fi
fi

if [[ -z "$RUN_SKYAWARE978" ]]; then
    stop_service
fi
if chk_enabled "${PIAWARE_MINIMAL}"; then
    stop_service
fi

mkdir -p /run/skyaware978

set -eo pipefail

# shellcheck disable=SC2016
exec "${s6wrap[@]}" skyaware978 \
  --connect 127.0.0.1:30978 \
  --json-dir "/run/skyaware978"
