#!/usr/bin/with-contenv sh
# shellcheck shell=sh

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${LAT}" ]; then
  echo "ERROR: LAT environment variable not set"
  EXITCODE=1
fi
if [ -z "${LONG}" ]; then
  echo "ERROR: LONG environment variable not set"
  EXITCODE=1
fi
if [ -n "${USERNAME+x}" ]; then
  echo "WARNING: USERNAME environment variable is DEPRECATED and does nothing"
fi
if [ -n "${PASSWORD+x}" ]; then
  echo "WARNING: PASSWORD environment variable is DEPRECATED and does nothing"
fi
if [ -z "${FEEDER_ID}" ]; then
  echo "INFO: no specific FEEDER_ID set, falling back to dynamic generated (/var/cache/piaware)"
  unset FEEDER_ID
else
  piaware-config feeder-id "${FEEDER_ID}"
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# If BINGMAPSAPIKEY is set, modify dump1090's config.js to include it
if [ ! -z "${BINGMAPSAPIKEY}" ]; then
  echo "INFO: setting BINGMAPSAPIKEY in /usr/share/dump1090-fa/html/config.js"
  
  sed \
    -i \
    "/^BingMapsAPIKey = /c\BingMapsAPIKey = "'"'"${BINGMAPSAPIKEY}"'"'";" \
    /usr/share/dump1090-fa/html/config.js

fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" >/etc/timezone
fi

# Set up piaware
piaware-config allow-mlat "${ALLOW_MLAT}"
piaware-config allow-modeac "${ALLOW_MODEAC}"
piaware-config allow-auto-updates no
piaware-config allow-manual-updates no

# Create log dir for piaware
mkdir -p /var/log/piaware
chown nobody:nogroup /var/log/piaware
