#!/command/with-contenv sh
# shellcheck shell=sh

# "dummy" SysV-style init script, to allow piaware to restart beast-splitter.
# piaware calls SysV init script to restart beast-splitter (package/fa_services.tcl invoke_service_action).
# this script allows that, while still using s6-supervise.
# pkilling beast-splitter causes s6-supervise to restart it.


case "$1" in
    restart)
    pkill beast-splitter
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
