#!/command/with-contenv sh
# shellcheck shell=sh

# "dummy" SysV-style init script, to allow piaware to restart dump1090.
# piaware calls SysV init script to restart dump1090 (package/fa_services.tcl invoke_service_action).
# this script allows that, while still using s6-supervise.
# pkilling dump1090 causes s6-supervise to restart it.


case "$1" in
    restart)
    pkill dump1090
    # sleep a bit to wait until dump1090 has restarted
    sleep 2
    # beast-splitter takes 60 seconds to reconnect, just restart it so it reconnects quicker
    pkill beast-splitter
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
