#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

PIAWARE_EXTRA_ARGS=""

if [ "$VERBOSE_LOGGING" = "true" ]; then
  PIAWARE_EXTRA_ARGS+="-debug"
fi

# shellcheck disable=SC2016
/usr/bin/piaware \
  -plainlog \
  "$PIAWARE_EXTRA_ARGS" \
  -statusfile /run/piaware/status.json \
  2>&1 | stdbuf -o0 awk '{print "[piaware] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
