#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

exec \
    /usr/bin/piaware \
    -plainlog \
    -statusfile /run/piaware/status.json \
    2>&1 | awk -W Interactive '{print "[piaware] " strftime("%m/%d/%Y %H:%M:%S", systime()) " " $0}'
