#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Don't continue if UAT_RECEIVER_HOST isn't set
if [[ -z "$UAT_RECEIVER_HOST" ]]; then
  sleep 86400
  exit 0
fi

socat -d -d TCP-LISTEN:30978,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30978}" \
 2>&1 | stdbuf -o0 awk '{print "[978raw-splitter] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
