#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Don't continue if BEASTHOST isn't set
if [[ -z "$BEASTHOST" ]]; then
  sleep 86400
  exit 0
fi

# Prepare beast-splitter command line
BEASTSPLITTER_BIN="/usr/local/bin/beast-splitter"
BEASTSPLITTER_CMD=("--net" "$BEASTHOST:${BEASTPORT:-30005}")
BEASTSPLITTER_CMD+=("--connect" "127.0.0.1:30004")

# shellcheck disable=SC2016
"${BEASTSPLITTER_BIN}" "${BEASTSPLITTER_CMD[@]}" \
  2>&1 | stdbuf -o0 awk '{print "[beast-splitter] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
