#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# When running with an external beast provider, we map the external beast
# provider on localhost:30005, to mimic dump1090 doing this.

EXTRA_SOCAT_ARGS=""

if [ "$VERBOSE_LOGGING" = "true" ]; then
  EXTRA_SOCAT_ARGS+="-d -d"
fi

if [ -z "${BEASTHOST}" ]; then
  sleep 3600
else
  exec \
    socat "$EXTRA_SOCAT_ARGS" TCP-LISTEN:30005,fork TCP:"${BEASTHOST}:${BEASTPORT}" \
    2>&1 | stdbuf -o0 awk '{print "[beastproxy] " $0}'
fi
