#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# When running with an external beast provider, we map the external beast
# provider on localhost:30005, to mimic dump1090 doing this.

# No dependencies

SOCAT_BIN="$(which socat)"
SOCAT_CMD=(-ls)

if [ "$VERBOSE_LOGGING" = "true" ]; then
  SOCAT_CMD+=("-d -d")
fi

SOCAT_CMD+=("TCP-LISTEN:30005,fork")
SOCAT_CMD+=("TCP:${BEASTHOST}:${BEASTPORT}")

if [ -z "${BEASTHOST}" ]; then
  sleep 3600
else
  # shellcheck disable=SC2016
  "${SOCAT_BIN}" "${SOCAT_CMD[@]}" \
    2>&1 | stdbuf -o0 awk '{print "[beastproxy] " $0}'
fi
