#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# When running with an external beast provider, we map the external beast
# provider on localhost:30005, to mimic dump1090 doing this.

if [ -z "${BEASTHOST}" ]; then
  sleep 3600
else
  exec \
    socat -d -d TCP-LISTEN:30005,fork TCP:"${BEASTHOST}:${BEASTPORT}" 2>&1 | awk -W Interactive '{print "[beastproxy] " $0}'
fi
