#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -e

DUMP1090_BIN=$(which dump1090)

if [[ -x "$DUMP1090_BIN" ]]; then

    echo "dump1090 detected: $DUMP1090_BIN. Not building."

else

    echo "dump1090 not found, performing first-run build."

    pushd /opt/dump1090 > /dev/null 2>&1

    # Make dump1090
    make showconfig \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:make showconfig] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    make all -j \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:make all] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    make faup1090 \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:make all] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    # Copy files
    cp -v view1090 dump1090 /usr/local/bin/ \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    cp -v faup1090 /usr/lib/piaware/helpers/ \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    
    mkdir -p /run/dump1090-fa
    mkdir -p /usr/share/dump1090-fa/html
    
    cp -a /src/dump1090/public_html/* /usr/share/dump1090-fa/html/ \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    
    mkdir -p /usr/share/skyaware/html
    
    cp -a /src/dump1090/public_html_merged/* /usr/share/skyaware/html \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    
    ldconfig \
        2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:ldconfig] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    
    popd > /dev/null 2>&1

fi
