#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2016

set -x
set +e

# If the feeder ID is not set, then don't make dump1090 as the user is likely trying to get a feeder-id
if [[ -n "$FEEDER_ID" ]]; then

    # Check to see if dump1090 exists
    DUMP1090_BIN=$(which dump1090)
    if [[ -x "$DUMP1090_BIN" ]]; then

        # If it does, don't build it

        echo "dump1090 detected: $DUMP1090_BIN. Not building."

        # Print dump1090-fa version
        # shellcheck disable=SC2016
        dump1090 --version \
            2>&1 | stdbuf -o0 awk '{print "[dump1090] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    else

        # If it does not, build it

        echo "dump1090 not found, performing first-run build."

        DUMP1090_VERSION=$(grep dump1090 /VERSIONS | cut -d " " -f 2)
        export DUMP1090_VERSION

        pushd /opt/dump1090 > /dev/null 2>&1

        # Make dump1090

        make showconfig BLADERF=yes RTLSDR=yes HACKRF=yes LIMESDR=yes \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:make showconfig] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

        make all BLADERF=yes RTLSDR=yes HACKRF=yes LIMESDR=yes -j \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:make all] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

        make faup1090 BLADERF=yes RTLSDR=yes HACKRF=yes LIMESDR=yes -j \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:make all] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

        # Copy files

        cp -v view1090 dump1090 /usr/local/bin/ \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

        cp -v faup1090 /usr/lib/piaware/helpers/ \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        
        mkdir -p /usr/share/dump1090-fa/html
        
        cp -a /opt/dump1090/public_html/* /usr/share/dump1090-fa/html/ \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        
        mkdir -p /usr/share/skyaware/html
        
        cp -a /opt/dump1090/public_html_merged/* /usr/share/skyaware/html \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:cp] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        
        # Update links

        ldconfig \
            2>&1 | stdbuf -o0 awk '{print "[firstrun:dump1090:ldconfig] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
        
        popd > /dev/null 2>&1

        # Print dump1090-fa version
        # shellcheck disable=SC2016
        dump1090 --version \
            2>&1 | stdbuf -o0 awk '{print "[dump1090] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

    fi
fi
