#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Remove existing piaware config
rm /etc/piaware.conf > /dev/null 2>&1 || true
touch /etc/piaware.conf

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [[ -n "${USERNAME}" ]]; then
  echo "WARNING: USERNAME environment variable is DEPRECATED and does nothing"
fi
if [[ -n "${PASSWORD}" ]]; then
  echo "WARNING: PASSWORD environment variable is DEPRECATED and does nothing"
fi
if [[ -n "${LAT}" ]]; then
  echo "WARNING: LAT environment variable is DEPRECATED and does nothing. Latitude is pulled from your FlightAware site configuration."
fi
if [[ -n "${LONG}" ]]; then
  echo "WARNING: LONG environment variable is DEPRECATED and does nothing. Longitude is pulled from your FlightAware site configuration."
fi
if [[ -n "${DUMP1090_DEVICE}" ]]; then
  echo "WARNING: DUMP1090_DEVICE environment variable is DEPRECATED, use RECEIVER_TYPE/RTLSDR_DEVICE_INDEX instead"
  set -x
  RTLSDR_DEVICE_INDEX="$DUMP1090_DEVICE"
  RECEIVER_TYPE="rtlsdr"
  set +x
fi
if [ -z "${FEEDER_ID}" ]; then
  echo "INFO: no specific FEEDER_ID set, falling back to dynamic generated (/var/cache/piaware)"
  unset FEEDER_ID
else
  piaware-config feeder-id "${FEEDER_ID}"
fi
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# If BINGMAPSAPIKEY is set, modify dump1090's config.js to include it
if [ -n "${BINGMAPSAPIKEY}" ]; then
  echo "INFO: setting BINGMAPSAPIKEY in /usr/share/dump1090-fa/html/config.js"
  
  sed \
    -i \
    "/^BingMapsAPIKey = /c\BingMapsAPIKey = "'"'"${BINGMAPSAPIKEY}"'"'";" \
    /usr/share/dump1090-fa/html/config.js

fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" >/etc/timezone
fi

# Set up piaware
piaware-config allow-auto-updates no
piaware-config allow-manual-updates no
piaware-config allow-mlat "${ALLOW_MLAT:-yes}"
piaware-config allow-modeac "${ALLOW_MODEAC:-yes}"
piaware-config mlat-results "${MLAT_RESULTS:-yes}"
piaware-config receiver-type "${RECEIVER_TYPE:-rtlsdr}"
piaware-config rtlsdr-ppm "${RTLSDR_PPM:-0}"
piaware-config rtlsdr-gain "${RTLSDR_GAIN:-max}"
piaware-config rtlsdr-device-index "${RTLSDR_DEVICE_INDEX:-0}"

if [[ -n "$BEASTHOST" ]]; then
  piaware-config receiver-type "relay"
  piaware-config receiver-host "$BEASTHOST"
  piaware-config receiver-port "${BEASTPORT:-30005}"
else
  piaware-config receiver-type "${RECEIVER_TYPE:-rtlsdr}"
fi

if [[ -n "$RADARCAPE_HOST" ]]; then
  piaware-config receiver-type "radarcape"
  piaware-config radarcape-host "$RADARCAPE_HOST"
fi


# Create log dir for piaware
mkdir -p /var/log/piaware
chown nobody:nogroup /var/log/piaware
