---
name: Pull Request

on:
  # Enable manual running of action if necessary
  workflow_dispatch:
  # Test build/deploy on PRs to main/master
  pull_request:
    # Only publish on push to main branch
    branches:
      - main
    # Don't trigger if it's just a documentation update
    paths:
      - "**.yml"
      - "rootfs/**"
      - "Dockerfile**"

jobs:
  test-build:
    name: Test
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      push_enabled: false
      build_version_specific: false
      build_platform_specific: false
      build_nohealthcheck: false
